language: android
jdk: oraclejdk11

android:
    components:
        - android-19
        - build-tools-19.1.0
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5
script:
    - make
